### ISSUE TITLE
关于封包的问题

### ISSUE THREAD

**Issue by aierblue** [pkuislm/PkPackage#2]
大佬你好，关于天津罪封包的那个Mosic.pk文件下爱线有一张cg仍旧有码，我不会程序，看大佬你能不能把它替换成无码的。
或者你能不能编译成可执行的exe告诉我怎么用，然后我自己替换

**Comment by pkuislm** [comment]
[PkPackageMaker.zip](https://github.com/pkuislm/PkPackage/files/15105669/PkPackageMaker.zip)
在命令行里调用，第一个参数是需要打包的文件夹，第二个参数是输出的封包的绝对路径，例如：
`./PkPackageMaker.exe "D:\Game\Amatsu\Patch\Mosic" "D:\Game\Amatsu\Patch\Mosic.pk"`
这个Mosic文件夹里放所有无码版的pb3文件，生成好以后直接替换原有的补丁文件即可
有其他问题可以继续在下面回复

**Comment by aierblue** [comment]
> [PkPackageMaker.zip](https://github.com/pkuislm/PkPackage/files/15105669/PkPackageMaker.zip) 在命令行里调用，第一个参数是需要打包的文件夹，第二个参数是输出的封包的绝对路径，例如： 这个Mosic文件夹里放所有版的pb3文件，生成好以后直接替换原有的补丁文件即可 有其他问题可以继续在下面回复`./PkPackageMaker.exe "D:\Game\Amatsu\Patch\Mosic" "D:\Game\Amatsu\Patch\Mosic.pk"`

ok，非常感谢，已经封包成功，游戏运行正常，再次感谢大佬
